name: Build
on:
  push:
    branches:
      - master
env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build
    strategy:
      matrix:
        kind: ["linux", "windows", "macos"]
        include:
          - kind: linux
            os: ubuntu-latest
          - kind: windows
            os: windows-latest
          - kind: macos
            os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.6.x"
          architecture: "x64"

      - name: Install conan && conan package tools
        run: |
          python -m pip install --upgrade pip
          pip install conan
          pip install conan_package_tools

      - name: Add conan repositories
        run: |
          conan remote add xpilot-project https://api.bintray.com/conan/jshannon/xpilot-project
          conan remote add xsquawkbox-public https://api.bintray.com/conan/akuneko/xsquawkbox
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

      - uses: actions/checkout@v1
        with:
          submodules: "recursive"

      - name: Create Build Environment
        run: cmake -E make_directory ${{ github.workspace }}/build

      - name: Initialize Conan
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: conan install $GITHUB_WORKSPACE --build missing

      - name: Configure CMake
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{ github.workspace }}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          name: ${{ matrix.kind }}
          path: ${{ github.workspace }}/build/lib/libafv_native.so

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: matrix.os == 'macos-latest'
        with:
          name: ${{ matrix.kind }}
          path: ${{ github.workspace }}/build/lib/libafv_native.dylib

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: matrix.os == 'windows-latest'
        with:
          name: ${{ matrix.kind }}
          path: ${{ github.workspace }}/build/bin/afv_native.dll
