name: Build

on:
  push:
    branches:
      - master

env:
  BUILD_TYPE: RelWithDebInfo
  QT_VERSION: 5.15.2

jobs:
  build:
    name: Build
    strategy:
      matrix:
        kind: ["linux", "windows", "macos"]
        include:
          - kind: linux
            os: ubuntu-latest
          - kind: windows
            os: windows-latest
          - kind: macos
            os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install conan
        run: |
          python3 -m pip install --upgrade pip
          pip3 install conan
          pip3 install conan_package_tools

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
            setup-python: false
            version: ${{ env.QT_VERSION }}

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create Build Environment
        run: cmake -E make_directory ${{ github.workspace }}/build

      - name: Initialize Conan
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: conan install $GITHUB_WORKSPACE --build missing

      - name: Configure CMake
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{ github.workspace }}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        with:
          name: ${{ matrix.kind }}
          path: ${{ github.workspace }}/build/lib/libafv_native.a

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: matrix.os == 'windows-latest'
        with:
          name: ${{ matrix.kind }}
          path: ${{ github.workspace }}/build/lib/afv_native.lib
