name: Build afv-native

on: 
  push:
  workflow_dispatch:

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          submodules: recursive
      - name: Bootstrap vcpkg
        run: |
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
      - name: Configure cmake
        run: |
          cmake -S . -B build/ -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build cmake
        run: |
          cmake --build build/
  build-osx-intel:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          submodules: recursive
      - name: Bootstrap vcpkg
        run: |
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
      - name: Configure cmake
        run: |
          cmake -S . -B build/ -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build cmake
        run: |
          cmake --build build/
  build-osx-arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          submodules: recursive
      - name: Bootstrap vcpkg
        run: |
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
      - name: Configure cmake
        run: |
          cmake -S . -B build/ -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_OSX_ARCHITECTURES=arm64 -DVCPKG_TARGET_TRIPLET=arm64-osx
      - name: Build cmake
        run: |
          cmake --build build/
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          submodules: recursive
      - name: Bootstrap vcpkg
        run: |
          ./vcpkg/bootstrap-vcpkg.bat -disableMetrics
      - name: Configure cmake
        run: |
          cmake -S . -B build/ -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build cmake
        run: |
          cmake --build build/