name: Release afv-native

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: atc-client
          submodules: recursive
      - name: Bootstrap vcpkg
        run: |
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
      - name: Configure cmake
        run: |
          cmake -S . -B build/ -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build cmake
        run: |
          cmake --build build/ --config Release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.so
  build-osx-intel:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: atc-client
          submodules: recursive
      - name: Bootstrap vcpkg
        run: |
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
      - name: Configure cmake (intel)
        run: |
          cmake -S . -B build_intel/ -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build cmake (intel)
        run: |
          cmake --build build_intel/ --config Release
      - name: Configure cmake (arm64)
        run: |
          cmake -S . -B build_arm/ -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_OSX_ARCHITECTURES=arm64 -DVCPKG_TARGET_TRIPLET=arm64-osx
      - name: Build cmake (arm64)
        run: |
          cmake --build build_arm/ --config Release
      - name: Create Universal Binary
        run: |
          lipo -create build_arm/libafv_native.dylib build_intel/libafv_native.dylib -output ./libafv_native.dylib
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: libafv_native.dylib
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: atc-client
          submodules: recursive
      - name: Bootstrap vcpkg
        run: |
          ./vcpkg/bootstrap-vcpkg.bat -disableMetrics
      - name: Configure cmake
        run: |
          cmake -S . -B build/ -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build cmake
        run: |
          cmake --build build/ --config Release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/Release/*.dll
